steps:
- name: 'python'
  args: ['pip3','install', '-r', 'requirements.txt', '--user']

- name: 'gcr.io/cloud-builders/gcloud']
    id: 'deployMyFunction'
  args: ['functions', 'deploy', 'my-function', '--source' , 'main.py', '--runtime' , 'python39' ,'--trigger-http']