steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - command-center
  - --region=europe-west3
  - --source=.
  - --trigger-bucket=input-json-bucket
  - --runtime=python39